name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: .NET test
        run: dotnet test --configuration Release

      - name: .NET publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

      - name: "Deploy to Azure App service"
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-experiments-github-actions-dev
          package: artifacts/
