name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: .NET test
        run: dotnet test --configuration Release

      - name: .NET publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: artifacts/

  deploy_dev:
    name: Deploy dev
    needs: build
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: dev

  deploy_prod:
    name: Deploy prod
    needs: deploy_dev
    uses: ./.github/workflows/step-deploy.yml
    with:
      env: prod
