name: Run every five minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    name: Run every five minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello World!"
